### ISSUE TITLE
Fix the option list mangling

### ISSUE THREAD

**Issue by Skillmon** [texno3/passopt#1]
Currently your code looks like it would break the behaviour of the `@raw@opt@` lists. Also, since it only alters the `@raw@opt@` list I guess it is only somewhat compatible with packages using that list and not the old list (which as of now should be the minority of packages). Anyway, if you're rebuilding the `@raw@opt` list you should not alter the contents in any way, so should protect against further expansion of the contents. And you should also define the normal `opt@` list in a way compatible to what the kernel would do to them (so fully expanded and space zapped).

With these out of the way, the more pressing issue seems to be that your package doesn't work at all. Consider the following MWE, which will show the complete option list as only `foo` after the package was loaded, instead of `my opt`, so your `\SetOptionsToPackage` didn't have any real effect on the options lists. I tested this with both `pdflatex` and `pdflatex-dev`:

```latex
\begin{filecontents}[overwrite]{\jobname.sty}
\ProvidesPackage{\@currname}

\DeclareOption{myopt}{\typeout{^^Jmyopt was used^^J}}
\DeclareOption*{}
\ProcessOptions\relax

\DeclareKeys{my opt .code = \typeout{^^Jmy opt was used^^J}, unknown .code = {}}
\ProcessKeyOptions\relax
\end{filecontents}

\documentclass{article}

\usepackage{passopt}
\SetOptionsToPackage*{\jobname}{my opt}
\usepackage[foo]{\jobname}
\expandafter\show\csname @raw@opt@\jobname.sty\endcsname

\stop
```

**Comment by Skillmon** [comment]
Sorry for the sort of noise, the second paragraph doesn't apply as I mixed up the argument order.

Still the option mangling to the raw lists is wrong, and the zapped lists are missing.

**Comment by Skillmon** [comment]
The following suggests a few changes to your package, namely it makes `\po_add_before_hook:nnn` faster by letting it use the `expl3` layer function instead of `\AddToHook`, and it fixes the handling of the options list to reflect the behaviour of the kernel for them (raw lists are unaltered, except for the first token being expanded once via `\expandafter`, and the normal option list being a zapped version of that).

```latex
\begin{filecontents}[overwrite]{\jobname.sty}
\ProvidesPackage{\@currname}

\DeclareOption{myopt}{\typeout{^^Jmyopt was used^^J}}
\ProcessOptions\relax

\DeclareKeys{my opt .code = \typeout{^^Jmy opt was used^^J}}
\ProcessKeyOptions\relax
\end{filecontents}

\documentclass{article}

\usepackage{passopt}

\makeatletter
\ExplSyntaxOn
\cs_set:Npn \po_add_before_hook:nnn #1#2
  { \hook_gput_code:nnn { #1/#2/before } { passopt } }
\RenewDocumentCommand \SetOptionsToPackage { s m m }
  { \__po_set_options:nnnnn { package } { sty } {#1} {#2} {#3} }
\RenewDocumentCommand \SetOptionsToClass { s m m }
  { \__po_set_options:nnnnn { class } { cls } {#1} {#2} {#3} }
\cs_new_protected:Npn \__po_set_options:nnnnn #1#2#3#4#5
  {
    \po_add_before_hook:nnn { #1 } {#5}
      {
        \cs_gset:cpx { @raw@opt@#5.#2 }
          {
            \IfBooleanTF {#3}
              { \exp_not:o {#4} }
              {
                \tl_if_blank:vTF { @raw@opt@#5.#2 }
                  { \exp_not:o {#4} }
                  { \exp_not:v { @raw@opt@#5.#2 } , \exp_not:n {#4} }
              }
          }
        \exp_args:Nc \protected@xdef { opt@#5.#2 }
          { \exp_last_unbraced:Nv \zap@space { @raw@opt@#5.#2 } ~ \@empty }
      }
  }
\ExplSyntaxOff
\makeatother

\SetOptionsToPackage*{my opt}{\jobname}
\usepackage[foo]{\jobname}

\stop
```

**Comment by texno3** [comment]
> The following suggests a few changes to your package, namely it makes `\po_add_before_hook:nnn` faster by letting it use the `expl3` layer function instead of `\AddToHook`, and it fixes the handling of the options list to reflect the behaviour of the kernel for them (raw lists are unaltered, except for the first token being expanded once via `\expandafter`, and the normal option list being a zapped version of that).
> 
> ```
> \begin{filecontents}[overwrite]{\jobname.sty}
> \ProvidesPackage{\@currname}
> 
> \DeclareOption{myopt}{\typeout{^^Jmyopt was used^^J}}
> \ProcessOptions\relax
> 
> \DeclareKeys{my opt .code = \typeout{^^Jmy opt was used^^J}}
> \ProcessKeyOptions\relax
> \end{filecontents}
> 
> \documentclass{article}
> 
> \usepackage{passopt}
> 
> \makeatletter
> \ExplSyntaxOn
> \cs_set:Npn \po_add_before_hook:nnn #1#2
>   { \hook_gput_code:nnn { #1/#2/before } { passopt } }
> \RenewDocumentCommand \SetOptionsToPackage { s m m }
>   { \__po_set_options:nnnnn { package } { sty } {#1} {#2} {#3} }
> \RenewDocumentCommand \SetOptionsToClass { s m m }
>   { \__po_set_options:nnnnn { class } { cls } {#1} {#2} {#3} }
> \cs_new_protected:Npn \__po_set_options:nnnnn #1#2#3#4#5
>   {
>     \po_add_before_hook:nnn { #1 } {#5}
>       {
>         \cs_gset:cpx { @raw@opt@#5.#2 }
>           {
>             \IfBooleanTF {#3}
>               { \exp_not:o {#4} }
>               {
>                 \tl_if_blank:vTF { @raw@opt@#5.#2 }
>                   { \exp_not:o {#4} }
>                   { \exp_not:v { @raw@opt@#5.#2 } , \exp_not:n {#4} }
>               }
>           }
>         \exp_args:Nc \protected@xdef { opt@#5.#2 }
>           { \exp_last_unbraced:Nv \zap@space { @raw@opt@#5.#2 } ~ \@empty }
>       }
>   }
> \ExplSyntaxOff
> \makeatother
> 
> \SetOptionsToPackage*{my opt}{\jobname}
> \usepackage[foo]{\jobname}
> 
> \stop
> ```

Thank you for your suggestion, I have made changes to the [code](https://github.com/texno3/passopt/blob/9594ac72fb4581e30d6646a4883959d2d7480595/passopt.sty#L10-L54), is it possible to add you to the contributors? If so please provide your name and email.

**Comment by Skillmon** [comment]
Hi, contributors is fine, as long as I'm not a maintainer :) Though I'm not really sure why you need my mail address if I'm just a contributor. Just say "Additional thanks to Jonathan P. Spratte for <whatever>" (that's my name) and it'd be fine. No need to put me as an author or anything.

While we're at nagging: `\po_add_before_hook:nnn` should be defined `protected` as well. Also your handling of the option lists should actually use local instead of global assignments, as LaTeX usually assigns to them locally as well (and your `\Clear...` macros do that as well).

**Comment by texno3** [comment]
Ok, I have changed the commands all to localized operations and will be releasing a new version soon.
